Enhance multiprocessing compatibility with non-RPi Linux distributions
Fix Klipper resonance calibration shutdown by forcing Python multiprocessing to use `fork` instead of `forkserver` (the default in some linux distributions).

Klipper’s input shaper calibration relies on `fork` semantics; `forkserver` causes pickling errors and aborts `TEST_RESONANCES` at the end of the frequency sweep.

It manifests in the logs as:

```
_pickle.PicklingError: Can't pickle local object <function ShaperCalibrate.background_process_exec.<locals>.wrapper at 0x7fa85a0a5590>
when serializing dict item '_target'

gcode.CommandError: Unable to obtain 'sensor_bulk_status' response

serialhdl.error: Unable to obtain 'sensor_bulk_status' response

serialhdl.error: Unable to obtain 'spi_transfer_response' response
```

OS info as reference:

```
nicomic@swanky
OS: EndeavourOS rolling rolling
Kernel: x86_64 Linux 6.18.6-zen1-1-zen
Uptime: 18h 36m
Packages: 1136
Shell: bash 5.3.9
Disk: 12G / 15G (85%)
CPU: Intel Celeron N2840 @ 2x 2.5823GHz
GPU: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e)
RAM: 1007MiB / 3821MiB
```

Python version:

`Python 3.14.2 (main, Jan  2 2026, 14:27:39) [GCC 15.2.1 20251112]`