Fix heartbeat waiting logic in palette2.py
Existing function causes a shutdown and the following error instantly when using PALETTE_CONNECT:

TypeError: '<' not supported between instances of 'NoneType' and 'float'

I refactored the waiting logic to catch this scenario and PALETTE_CONNECT now works (tested with a PALETTE 2 and a PALETTE 2 PRO)